version: "3.8"
services:
  keycloak:
    image: keycloak
    build:
      context: ../
      dockerfile: ./dev/Dockerfile
    volumes:
      - type: bind
        source: ../theme
        target: /opt/jboss/keycloak/themes/europeana
    ports:
      - "10001:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD
  smtp:
    image: namshi/smtp
    expose:
      - "25"
